Add clone macro
atins-dev/onvif-rs pull request #2
Opened 2021-06-18 00:40 UTC by powerory

- Replace type alias with fully type re-define to solve the problem in building SOAP message
- Add #[derive(Clone)] for some structs used in ignis-onvif

2021-06-18 00:49 UTC, powerory commented
commit 746446f은 PR#1에서 작업한 내용과 같은 내용인데 별도 commit으로 남아 있었네요. 원인이 무엇인지 모르겠습니다.;;

2021-06-22 01:20 UTC, Shalom92 approved these changes

2021-06-22 01:22 UTC, wonchulee requested changes
커밋 작성하신 베이스가 최신이 아닌 것 같아보입니다. 리베이스 후 다시 업데이트 부탁드릴게요

2021-06-22 01:31 UTC, powerory commented
> 커밋 작성하신 베이스가 최신이 아닌 것 같아보입니다. 리베이스 후 다시 업데이트 부탁드릴게요

아 리베이스를 깜빡해서 이전 PR의 commit이 같이 있는 거였군요. ㅠㅠ

2021-06-22 02:00 UTC, merged