Event prop
atins-dev/onvif-rs pull request #29
Opened 2023-02-08 07:07 UTC by ski0090

event property를 list의 형태로 가져오는 api를 추가한다

2023-02-08 07:49 UTC, powerory requested changes

2023-02-08 07:49 UTC, powerory commented on schema/src/transport.rs
> +pub async fn request_event_properties<T: Transport>(
p2: 너무 특정 동작에 특화되도록 구현되었네요. 그냥 deser를 하지 않고 리턴하게 함수를 구현하는 것이 좋을 것 같습니다.

2023-02-08 07:49 UTC, powerory commented on schema/src/event.rs
> +) -> Result<Vec<String>, transport::Error> {
p2: 이부분도 req에 대한 response가 특정 타입으로 바뀌는 것은 onvif-rs의 전체적인 스킴에 위반되는 내용입니다.
리턴 타입은 마찬가지로 GetEventPropertiesResponse으로 해주시고, 필요하면 해당 struct의 내용을 변경 한 뒤 새롭게 구현된 request 함수를 통해 파싱한 뒤 내용을 채워서 리턴하게 해주세요.

2023-02-08 07:49 UTC, powerory commented on schema/src/transport.rs
> +pub async fn request_event_properties<T: Transport>(
아니면 yasere::de가 아닌 custom하게 구현한 deser를 trait으로 정의해서 리턴타입을 S: YaDeserialize한 것처럼 구현해주면 조금 더 이쁘게 구현될 것 같네요.

2023-02-13 07:08 UTC, ski0090 commented on schema/src/transport.rs
> +pub async fn request_event_properties<T: Transport>(
적용하였습니다

2023-02-13 07:08 UTC, ski0090 commented on schema/src/event.rs
> +) -> Result<Vec<String>, transport::Error> {
적용하였습니다

2023-02-13 08:40 UTC, powerory approved these changes

2023-02-13 08:40 UTC, powerory commented on schema/src/transport.rs
> -
p5: 이건 원래 있던 코드 부분이니 공백이라도 원복하는 것이 좋을 것 같습니다.

2023-02-13 08:40 UTC, powerory commented
LGTM

2023-02-13 09:23 UTC, merged